<a href="https://colab.research.google.com/github/AnkitGole007/CS541-DeepLearning/blob/hw4/pytorch_pre-requisite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

z = torch.zeros((2,3),dtype=torch.int16)
print(z)

i = torch.ones((5, 3), dtype=torch.int16)
print(i)

torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print('A random tensor:')
print(r1)

r2 = torch.rand(2, 2)
print('\nA different random tensor:')
print(r2) # new values

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print('\nAnd another random tensor:')
print(r3) # new values

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

And another random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [ ]:
r1+r2
r = (torch.rand(2,2)-0.5)
print(r)

print(torch.abs(r))

print(torch.std_mean(r))
print(torch.max(r))

tensor([[-0.0784, -0.4309],
        [-0.2668, -0.0953]])
tensor([[0.0784, 0.4309],
        [0.2668, 0.0953]])
(tensor(0.1656), tensor(-0.2179))
tensor(-0.0784)


In [ ]:
import torch.nn as nn
import torch.optim as optim

X = torch.randn(100, 1)    # 100 samples, 1 feature
y = 3 * X + 2 + 0.1 * torch.randn(100, 1)

class LinearRegression(nn.Module):
  def __init__(self):
    super(LinearRegression, self).__init__()
    self.linear = nn.Linear(1,1)

  def forward(self, x):
    return self.linear(x)

model = LinearRegression()
loss = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

num_epochs = 1000
for epoch in range(num_epochs):
  y_pred = model(X)
  l = loss(y_pred,y)

  optimizer.zero_grad()
  l.backward()
  optimizer.step()
  if (epoch+1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {l.item():.4f}')

Epoch [100/1000], Loss: 0.2628
Epoch [200/1000], Loss: 0.0172
Epoch [300/1000], Loss: 0.0091
Epoch [400/1000], Loss: 0.0088
Epoch [500/1000], Loss: 0.0088
Epoch [600/1000], Loss: 0.0088
Epoch [700/1000], Loss: 0.0088
Epoch [800/1000], Loss: 0.0088
Epoch [900/1000], Loss: 0.0088
Epoch [1000/1000], Loss: 0.0088


In [ ]:
X = torch.randn(100,2)
y = torch.randint(0,3,(100,))

class SoftmaxRegression(nn.Module):
  def __init__(self):
     super(SoftmaxRegression, self).__init__()
     self.linear = nn.Linear(2,3)

  def forward(self, x):
    return self.linear(x)

  def predict(self, x):
    y_pred = self.forward(x)
    return torch.argmax(y_pred, dim=1)

num_epochs = 1000
model = SoftmaxRegression()
loss = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

for epoch in range(num_epochs):
  y_pred = model(X)
  l = loss(y_pred,y)

  optimizer.zero_grad()
  l.backward()
  optimizer.step()

  if (epoch+1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {l.item():.4f}')
        print(model.predict(X)[1])

Epoch [100/1000], Loss: 1.2787
tensor(2)
Epoch [200/1000], Loss: 1.1914
tensor(2)
Epoch [300/1000], Loss: 1.1362
tensor(2)
Epoch [400/1000], Loss: 1.1041
tensor(2)
Epoch [500/1000], Loss: 1.0871
tensor(2)
Epoch [600/1000], Loss: 1.0786
tensor(2)
Epoch [700/1000], Loss: 1.0745
tensor(2)
Epoch [800/1000], Loss: 1.0725
tensor(2)
Epoch [900/1000], Loss: 1.0716
tensor(2)
Epoch [1000/1000], Loss: 1.0711
tensor(2)


In [ ]:
import numpy as np
from torch.utils.data import DataLoader, TensorDataset, random_split

train_images = np.load("/content/drive/MyDrive/Colab Notebooks/datasets/fashion_mnist_train_images.npy")
train_labels = np.load("/content/drive/MyDrive/Colab Notebooks/datasets/fashion_mnist_train_labels.npy")
test_images = np.load("/content/drive/MyDrive/Colab Notebooks/datasets/fashion_mnist_test_images.npy")
test_labels = np.load("/content/drive/MyDrive/Colab Notebooks/datasets/fashion_mnist_test_labels.npy")

train_images_tensor = torch.from_numpy(train_images)
train_labels_tensor = torch.from_numpy(train_labels).long()
test_images_tensor = torch.from_numpy(test_images)
test_labels_tensor = torch.from_numpy(test_labels).long()

train_size = int(0.8 * len(train_images_tensor))
val_size = len(train_images_tensor) - train_size

train_dataset, val_dataset = random_split(TensorDataset(train_images_tensor, train_labels_tensor),[train_size,val_size])

batch_size = 64

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(TensorDataset(test_images_tensor, test_labels_tensor), batch_size=batch_size, shuffle=False)

class SoftmaxRegression(nn.Module):
  def __init__(self, input_size = 784, hidden_size = 128, output_size = 10):
     super(SoftmaxRegression, self).__init__()
     self.fn1 = nn.Linear(input_size,hidden_size)
     self.fn2 = nn.Linear(hidden_size,output_size)

  def forward(self, x):
    x = x.view(-1, 784)
    x = torch.relu(self.fn1(x))
    x = self.fn2(x)
    return x

epsilon = 0.001
alpha = 0.01
epochs = 100

model = SoftmaxRegression()
loss = nn.CrossEntropyLoss()
optimizer  = optim.SGD(model.parameters(),lr=epsilon,weight_decay=alpha)

def train(model, train_loader, val_loader, loss, optimizer, epochs):
  for epoch in range(epochs):
    model.train()
    train_loss = 0
    for image,label in train_loader:
      optimizer.zero_grad()
      y_pred = model(image)
      l = loss(y_pred,label)
      l.backward()
      optimizer.step()
      train_loss += l.item()

    model.eval()
    val_loss = 0
    total = 0
    count = 0

    with torch.no_grad():
      for image,label in val_loader:
        outputs = model(image)
        l = loss(outputs, label)
        val_loss += l
        predicted = torch.argmax(outputs, 1)
        total = label.size(0)
        count = (predicted == label).sum().item()

    if (epoch+1)%10 == 0:
      print(f"Epoch [{epoch+1}/{epochs}], Train Loss: {train_loss/len(train_loader):.4f}, "
            f"Val Loss: {val_loss/len(val_loader):.4f}, Val Accuracy: {100 * count / total:.2f}%")

train(model, train_loader, val_loader, loss, optimizer, epochs)

def evaluate(model, test_loader, loss):
  model.eval()
  test_loss = 0
  total = 0
  count = 0

  with torch.no_grad():
    for image,label in val_loader:
      outputs = model(image)
      l = loss(outputs, label)
      test_loss += l
      predicted = torch.argmax(outputs, 1)
      total = label.size(0)
      count = (predicted == label).sum().item()
  print(f"Test Loss: {test_loss/len(test_loader):.4f}, Test Accuracy: {100 * count / total:.2f}%")

evaluate(model, test_loader, loss)

Epoch [10/100], Train Loss: 0.3758, Val Loss: 0.4549, Val Accuracy: 78.12%
Epoch [20/100], Train Loss: 0.3180, Val Loss: 0.3954, Val Accuracy: 90.62%
Epoch [30/100], Train Loss: 0.2863, Val Loss: 0.3879, Val Accuracy: 81.25%
Epoch [40/100], Train Loss: 0.2621, Val Loss: 0.3723, Val Accuracy: 87.50%
Epoch [50/100], Train Loss: 0.2464, Val Loss: 0.3896, Val Accuracy: 96.88%
Epoch [60/100], Train Loss: 0.2315, Val Loss: 0.3788, Val Accuracy: 96.88%
Epoch [70/100], Train Loss: 0.2170, Val Loss: 0.4145, Val Accuracy: 87.50%
Epoch [80/100], Train Loss: 0.2070, Val Loss: 0.3902, Val Accuracy: 93.75%
Epoch [90/100], Train Loss: 0.1977, Val Loss: 0.4592, Val Accuracy: 87.50%
Epoch [100/100], Train Loss: 0.1856, Val Loss: 0.4191, Val Accuracy: 96.88%
Test Loss: 0.5019, Test Accuracy: 96.88%
